local presets = {
    ["adventure"] = {"Preset: Adventure", "Equipment Checks - Complexity 9"},
    ["agonize-twtw"] = {"Preset: Agonize 2020", "Guarded Checks", "Relics in Set Locations", "Maximizes backtracking"},
    ["any-percent"] = {"Preset: Any Percent", "Guarded Checks - Complexity 6", "Richter and Relic Skip Required", "Death Skip allowed",
                    "Bat and Wolf in first castle"},
    ["aperture"] = {"Preset: Aperture", "Guarded Checks - Complexity 8", "Shortcuts and Teleporters are open",
                    "Fire of Bat Requires Transformation", "Force of Echo needs Wolf + Holy symbol",
                    "Must find portal spell with all 5 Vlads", "Reverse Library card enabled"},
    ["bat-master"] = {"Preset: Bat Master", "Guarded+ checks - Complexity 1", "All Bat Relics in First Castle"},
    ["battle-mage"] = {"Preset: Battle Mage", "Guarded+ Checks - Complexity 8", "Four Beasts cost 70 MP",
                    "Sword spells left-right-up button"},
    ["beyond"] = {"Preset: Beyond", "Guarded Checks - Complexity 8", "New items", "Castle Key unlocks all Teleporters",
                    "Mannequin can bypass blue doors"},
    ["big-toss"] = {"Preset: Big Toss", "Guarded Checks - Complexity 5", "Toadstool causes big toss", "High Potion and Toadstool are infinite"},
    ["boss-rush"] = {"Preset: Boss Rush", "Start with lower tier weapons", "Life max ups don't heal", "Intended as a Arcade mode"},
    ["bounty-hunter"] = {"Preset: Bounty Hunter", "Guarded Checks - Complexity 5", "Vlads are held by Target enemies", 
                    "Reverse Library card enabled"},
    ["brawler"] = {"Preset: Brawler", "Guarded Checks - Complexity 7", "Fist combat is the Focus", "Entrance-Outer Wall teleport open", 
                    "Some spells are removed"},
    ["breach"] = {"Preset: Breach", "Guarded Checks - Complexity 5", "Start with Nimble loadout", "Aperture castle Layout", "Start with all Vlads", 
                "Must find the Portal Spell", "Reverse Library card enabled"},
    ["casual"] = {"Preset: Casual", "Guarded Checks - Complexity 1"},
    ["chaos-lite"] = {"Preset: Chaos Lite", "Guarded Checks - Complexity 1", "April Fools Preset", "Target Enemies holds the Vlads", "Reverse Library card enabled"},
    ["chimera"] = {"Preset: Chimera",  "Guarded Checks - Complexity 8", "Enhanced Wolf, Mist cost 0MP",  "Gas Cloud Grants Warlock buff", "Godspeed Boots Enabled"},
    ["cornivus"] = {"Preset: Cornivus", "Guarded Checks - Complexity 8", "Lycanthrope with 2nd Castle Start", "All bosses and Vlads Required"},
    ["cursed-night"] = {"Preset: Cursed Night", "Guarded Checks - Complexity 6", "Start Cursed", "Eldritch Shield after Dopp10", "Coral Circlet Removes Cursed status"},
    ["dog-life"] = {"Preset: Dog Life", "Guarded Checks - Complexity 9", "Wolf only, new relics", "Many relics modify wolf movement"},
    ["empty-hand"] = {"Preset: Empty Hand", "Guarded Checks - Complexity 9", "April Fools Preset", "No Equipment challenge mode"},
    ["expedition"] = {"Preset: Expedition", "Equipment Checks - Complexity 9", "Start with Nimble loadout", "Reverse Library card enabled"},
    ["first-castle"] = {"Preset: First Castle", "Guarded Checks - Complexity 5", "Shortcuts are open from the start", "Start with 2 Library cards", 
                    "Glasses+Vlads grants access to the end", "Save Richter to teleport the end"},
    ["gem-farmer"] = {"Preset: Gem Farmer", "Guarded Checks - Complexity 1", "April Fools Preset", "Progression is bought at the Shop"},
    ["glitch"] = {"Preset: Glitch"},
    ["glitch-leg"] = {"Preset: Glitch Legacy"},
    ["glitchmaster"] = {"Preset: Glitchmaster"},
    ["grand-tour"] = {"Preset: Grand Tour", "Scenic Checks - Complexity 8", "Intended to show off the castle"},
    ["guarded-og"] = {"Preset: Guarded O.G.", "Guarded Checks - Complexity 1", "Important items are vanilla", "Bat, Mist and Jewel are in 1st castle", "Good Starting preset"},
    ["hitman"] = {"Preset: Hitman", "Guarded Checks - Complexity 1", "Bounty Hunter Variant", "Start with all Targets", "Reverse Library card enabled"},
    ["leg-day"] = {"Preset: Leg Day", "Guarded Checks - Complexity 7", "Start with Leap Stone and infinite jumps", "Backdash longer with invincibility", "Glasses and Spike Breaker","needed for 2nd Castle"},
    ["lucky-sevens"] = {"Preset: Lucky Sevens", "Guarded Checks - Complexity 7", "Start with 77 in all stats", "7 random Relics at the start", "77% chance for Drops", "All Shortcuts and some Teleporters open",
                    "Enemies have a chance to drop relics", "No Prologue"},
    ["lycanthrope"] = {"Preset: Lycanthrope", "Guarded Checks - Complexity 8", "Start with Full Wolf", "Wolf Reduced cost", "Death Skip is Intended"},
    ["magic-mirror"] = {"Preset: Magic Mirror", "Guarded+ Checks - Compleity 6", "Entrance-Outer Wall teleport open", "Modified Castle", "X+Triangle to teleport to other castle"},
    ["max-rando"] = {"Preset: Max Rando", "Scenic Checks - Complexity 1", "Everything possible is randomized", "Must find portal spell with all 5 Vlads"},
    ["mirror-breaker"] = {"Preset: Mirror Breaker", "Guarded+ Checks - Compleity 3", "All Bosses Required", "Start with Grav Boots, Potions and Mirror", "X+Triangle to teleport to other castle"},
    ["mobility"] = {"Preset: Mobility", "Extended Checks - Complexity 6", "Start with all Movement", "Magic Mirror Variant", "Transformations cost Less", "Enemy Stat Rando+Shop price rando", 
                    "X+Triangle to teleport to other castle"},
    ["nimble"] = {"Preset: Nimble", "Guarded Checks - Complexity 5", "Bat+Leap stone+Gravity boots", "Duplicator+Manna Prism+Buffalo Star"},
    ["nimble-lite"] = {"Preset: Nimble Lite", "Guarded Checks - Complexity 5", "Nimble Variant with Random Gear"},
    ["og"] = {"Preset: O.G.", "Classic Checks - Complexity 1", "Important items are vanilla", "Bat, Mist and Jewel are in 1st castle"},
    ["open"] = {"Preset: Open", "Guarded Checks - Complexity 6", "Start in a Random location", "All shortcuts and Teleporters open"},
    ["oracle"] = {"Preset: Oracle", "Guarded Checks - Complexity 9", "Removes all RNG", "Enemies always will drop their items", "Rings are Replaced by Silver Key", "Vlads replaced by Gold Key"},
    ["rampage"] = {"Preset: Rampage", "Guarded Checks - Complexity 6", "Target confirmed Variant", "Familiar cards Show targets", "All shortcuts and Teleporters open", 
                "All bosses and Vlads Required", "Reverse Library card enabled"},
    ["rat-race"] = {"Preset: Rat Race", "Guarded Checks - Complexity 9", "April Fools Preset 2023", "Just tryin to make a buck"},
    ["recycler"] = {"Preset: Recycler", "Guarded Checks - Complexity 6", "Duplicate relics", "3 New Vlads added", "Need 6 Vlads to open Shaft's Door", "Start in 2nd Castle"},
    ["safe"] = {"Preset: Safe", "Guarded Checks - Complexity 9", "Item stat rando Enabled", "Requires no special knowledge"},
    ["safe-stwo"] = {"Preset: Safe Season 2", "Guarded Checks - Complexity 8", "Mimics how Safe was in Season 2", "Requires no special knowledge"},
    ["scavenger"] = {"Preset: Scavenger", "Guarded Checks - Complexity 9", "Enemy Drops Disabled", "Equipment can be found in the castle"},
    ["seeker"] = {"Preset: Seeker", "Guarded Checks - Complexity 7", "Portal Spell is always end of chain", "2nd castle Teleporter is Broken", "LC Guarenteed before Death", 
                "Scimitars always drop Aquamarine"},
    ["sequence-breaker"] = {"Preset: Sequence Breaker", "Guarded Checks - Complexity 8", "Requires knowledge of sequence breaks", "All Forms of Dive kicks are in logic"},
    ["sight-seer"] = {"Preset: Sight Seer", "Extended Checks - Complexity 7", "Simple and casual preset"},
    ["spellbound"] = {"Preset: Spellbound", "Guarded Checks - Complexity 9", "Spells locked by Familiar Cards", "Relics are hidden in scrolls"}, --Why is this still here?
    ["summoner"] = {"Preset: Summoner", "Guarded Checks - Complexity 7", "Familiars start at level 99", "Monster vials buffed", "SWORD OF BRAWN"},
    ["target-confirmed"] = {"Preset: Target Confirmed", "Guarded Checks - Complexity 6", "Bounty Hunter Variant", "Familiar cards Required for Vlads", "Higher odds to get Drop", 
                    "Reverse Library card enabled"},
    ["third-castle"] = {"Preset: Third Castle", "Guarded Checks - Complexity 9", "April Fools Preset", "Randomizes Tileset Data"},
    ["timeline"] = {"Preset: Timeline", "Guarded Checks - Complexity 8", "Random Relics are given over time"},
    ["vanilla"] = {"Preset: Vanilla", "Essentially the vanilla game", "Allows options to be used"},
    ["warlock"] = {"Preset: Warlock", "Guarded Checks - Complexity 6", "Mist is free", "Spells cost less",  "Buffed intelligence"}

}

return presets
